"""
Unit tests for domain models in dmca-light-api.

Generated by The Anvil S+++ Constitutional AGI Genesis Engine.
Version: 0.1.0

[!] CRITICAL: This file is auto-generated. Do not edit manually.
    To modify tests, update the Anvil specification YAML and regenerate.
"""
import pytest
from datetime import datetime
from pydantic import ValidationError

from app.models import (
    Material,
    ExcitonResult,
    PaginatedResponse,
    ErrorResponse,
    SuccessResponse,
)


class TestMaterial:
    """Test cases for Material domain model"""

    def test_create_valid_material(self):
        """Test creating a valid Material instance"""
        data = {
            "id": 1,
            "name": "test_name",
            "formula": "test_formula",
            "band_gap": 1.0,
            "epsilon": 1.0,
            "effective_mass_e": 1.0,
            "effective_mass_h": 1.0,
            "lattice_constant": 1.0,
        }

        instance = Material(**data)

        # Verify instance creation
        assert instance is not None
        assert isinstance(instance, Material)

        # Verify all field values
        assert instance.id == data["id"]
        assert hasattr(instance, "id")
        assert instance.name == data["name"]
        assert hasattr(instance, "name")
        assert instance.formula == data["formula"]
        assert hasattr(instance, "formula")
        assert instance.band_gap == data["band_gap"]
        assert hasattr(instance, "band_gap")
        assert instance.epsilon == data["epsilon"]
        assert hasattr(instance, "epsilon")
        assert instance.effective_mass_e == data["effective_mass_e"]
        assert hasattr(instance, "effective_mass_e")
        assert instance.effective_mass_h == data["effective_mass_h"]
        assert hasattr(instance, "effective_mass_h")
        assert instance.lattice_constant == data["lattice_constant"]
        assert hasattr(instance, "lattice_constant")

    def test_material_serialization(self):
        """Test Material JSON serialization/deserialization"""
        data = {
            "id": 1,
            "name": "test_name",
            "formula": "test_formula",
            "band_gap": 1.0,
            "epsilon": 1.0,
            "effective_mass_e": 1.0,
            "effective_mass_h": 1.0,
            "lattice_constant": 1.0,
        }

        # Create instance
        instance = Material(**data)
        assert instance is not None

        # Serialize to dict
        serialized = instance.dict()
        assert isinstance(serialized, dict)
        assert len(serialized) > 0
        assert "id" in serialized
        assert "name" in serialized
        assert "formula" in serialized
        assert "band_gap" in serialized
        assert "epsilon" in serialized
        assert "effective_mass_e" in serialized
        assert "effective_mass_h" in serialized
        assert "lattice_constant" in serialized

        # Deserialize back
        deserialized = Material(**serialized)
        assert deserialized is not None
        assert isinstance(deserialized, Material)
        assert deserialized.id == instance.id
        assert deserialized.name == instance.name
        assert deserialized.formula == instance.formula
        assert deserialized.band_gap == instance.band_gap
        assert deserialized.epsilon == instance.epsilon
        assert deserialized.effective_mass_e == instance.effective_mass_e
        assert deserialized.effective_mass_h == instance.effective_mass_h
        assert deserialized.lattice_constant == instance.lattice_constant

    def test_material_missing_required_fields(self):
        """Test Material validation fails with missing required fields"""
        # Missing id
        data = {
            "name": "test",
            "formula": "test",
            "band_gap": 1.0,
            "epsilon": 1.0,
            "effective_mass_e": 1.0,
            "effective_mass_h": 1.0,
            "lattice_constant": 1.0,
        }
        with pytest.raises(ValidationError):
            Material(**data)

        # Missing name
        data = {
            "id": 1,
            "formula": "test",
            "band_gap": 1.0,
            "epsilon": 1.0,
            "effective_mass_e": 1.0,
            "effective_mass_h": 1.0,
            "lattice_constant": 1.0,
        }
        with pytest.raises(ValidationError):
            Material(**data)

        # Missing formula
        data = {
            "id": 1,
            "name": "test",
            "band_gap": 1.0,
            "epsilon": 1.0,
            "effective_mass_e": 1.0,
            "effective_mass_h": 1.0,
            "lattice_constant": 1.0,
        }
        with pytest.raises(ValidationError):
            Material(**data)







    def test_material_xss_prevention(self):
        """Test Material XSS attack prevention via input sanitization"""
        # XSS payloads to test
        xss_payloads = [
            "<script>alert('xss')</script>",
            "javascript:alert('xss')",
            "<img src=x onerror=alert('xss')>",
            "' OR '1'='1",
        ]

        for payload in xss_payloads:
            data = {
                "id": 1,
                "name": payload,
                "formula": "test",
                "band_gap": 1.0,
                "epsilon": 1.0,
                "effective_mass_e": 1.0,
                "effective_mass_h": 1.0,
                "lattice_constant": 1.0,
            }

            # Should either sanitize or raise ValidationError
            try:
                instance = Material(**data)
                # Verify sanitization occurred (whitespace stripped, no null bytes)
                assert '\x00' not in instance.name
                assert instance.name.strip() == instance.name
                # Verify not just whitespace
                if payload.strip():
                    assert len(instance.name) > 0
            except ValidationError:
                # Validation rejection is also acceptable
                pass

        for payload in xss_payloads:
            data = {
                "id": 1,
                "name": "test",
                "formula": payload,
                "band_gap": 1.0,
                "epsilon": 1.0,
                "effective_mass_e": 1.0,
                "effective_mass_h": 1.0,
                "lattice_constant": 1.0,
            }

            # Should either sanitize or raise ValidationError
            try:
                instance = Material(**data)
                # Verify sanitization occurred (whitespace stripped, no null bytes)
                assert '\x00' not in instance.formula
                assert instance.formula.strip() == instance.formula
                # Verify not just whitespace
                if payload.strip():
                    assert len(instance.formula) > 0
            except ValidationError:
                # Validation rejection is also acceptable
                pass


    def test_material_null_byte_prevention(self):
        """Test Material null byte injection prevention"""
        data = {
            "id": 1,
            "name": "test\x00injection",
            "formula": "test",
            "band_gap": 1.0,
            "epsilon": 1.0,
            "effective_mass_e": 1.0,
            "effective_mass_h": 1.0,
            "lattice_constant": 1.0,
        }
        with pytest.raises(ValidationError) as exc_info:
            Material(**data)
        assert "null bytes" in str(exc_info.value).lower()

        data = {
            "id": 1,
            "name": "test",
            "formula": "test\x00injection",
            "band_gap": 1.0,
            "epsilon": 1.0,
            "effective_mass_e": 1.0,
            "effective_mass_h": 1.0,
            "lattice_constant": 1.0,
        }
        with pytest.raises(ValidationError) as exc_info:
            Material(**data)
        assert "null bytes" in str(exc_info.value).lower()


    def test_material_whitespace_only_prevention(self):
        """Test Material whitespace-only string prevention"""
        data = {
            "id": 1,
            "name": "   ",  # Whitespace only
            "formula": "test",
            "band_gap": 1.0,
            "epsilon": 1.0,
            "effective_mass_e": 1.0,
            "effective_mass_h": 1.0,
            "lattice_constant": 1.0,
        }
        with pytest.raises(ValidationError) as exc_info:
            Material(**data)
        assert "whitespace" in str(exc_info.value).lower()

        data = {
            "id": 1,
            "name": "test",
            "formula": "   ",  # Whitespace only
            "band_gap": 1.0,
            "epsilon": 1.0,
            "effective_mass_e": 1.0,
            "effective_mass_h": 1.0,
            "lattice_constant": 1.0,
        }
        with pytest.raises(ValidationError) as exc_info:
            Material(**data)
        assert "whitespace" in str(exc_info.value).lower()



class TestExcitonResult:
    """Test cases for ExcitonResult domain model"""

    def test_create_valid_excitonresult(self):
        """Test creating a valid ExcitonResult instance"""
        data = {
            "id": 1,
            "material_id": 1,
            "binding_energy": 1.0,
            "bohr_radius": 1.0,
            "calculated_at": datetime.utcnow(),
        }

        instance = ExcitonResult(**data)

        # Verify instance creation
        assert instance is not None
        assert isinstance(instance, ExcitonResult)

        # Verify all field values
        assert instance.id == data["id"]
        assert hasattr(instance, "id")
        assert instance.material_id == data["material_id"]
        assert hasattr(instance, "material_id")
        assert instance.binding_energy == data["binding_energy"]
        assert hasattr(instance, "binding_energy")
        assert instance.bohr_radius == data["bohr_radius"]
        assert hasattr(instance, "bohr_radius")
        assert instance.calculated_at == data["calculated_at"]
        assert hasattr(instance, "calculated_at")

    def test_excitonresult_serialization(self):
        """Test ExcitonResult JSON serialization/deserialization"""
        data = {
            "id": 1,
            "material_id": 1,
            "binding_energy": 1.0,
            "bohr_radius": 1.0,
            "calculated_at": "2025-01-01T00:00:00",
        }

        # Create instance
        instance = ExcitonResult(**data)
        assert instance is not None

        # Serialize to dict
        serialized = instance.dict()
        assert isinstance(serialized, dict)
        assert len(serialized) > 0
        assert "id" in serialized
        assert "material_id" in serialized
        assert "binding_energy" in serialized
        assert "bohr_radius" in serialized
        assert "calculated_at" in serialized

        # Deserialize back
        deserialized = ExcitonResult(**serialized)
        assert deserialized is not None
        assert isinstance(deserialized, ExcitonResult)
        assert deserialized.id == instance.id
        assert deserialized.material_id == instance.material_id
        assert deserialized.binding_energy == instance.binding_energy
        assert deserialized.bohr_radius == instance.bohr_radius

    def test_excitonresult_missing_required_fields(self):
        """Test ExcitonResult validation fails with missing required fields"""
        # Missing id
        data = {
            "material_id": 1,
            "binding_energy": 1.0,
            "bohr_radius": 1.0,
            "calculated_at": datetime.utcnow(),
        }
        with pytest.raises(ValidationError):
            ExcitonResult(**data)

        # Missing material_id
        data = {
            "id": 1,
            "binding_energy": 1.0,
            "bohr_radius": 1.0,
            "calculated_at": datetime.utcnow(),
        }
        with pytest.raises(ValidationError):
            ExcitonResult(**data)

        # Missing binding_energy
        data = {
            "id": 1,
            "material_id": 1,
            "bohr_radius": 1.0,
            "calculated_at": datetime.utcnow(),
        }
        with pytest.raises(ValidationError):
            ExcitonResult(**data)






    def test_excitonresult_foreign_key_validation(self):
        """Test ExcitonResult foreign key validation"""
        # Valid foreign key for material_id
        data_valid = {
            "id": 1,
            "material_id": 1,
            "binding_energy": 1.0,
            "bohr_radius": 1.0,
            "calculated_at": datetime.utcnow(),
        }
        instance = ExcitonResult(**data_valid)
        assert instance.material_id == 1

        # Invalid foreign key (non-positive)
        data_invalid = {
            "id": 1,
            "material_id": -1,  # Invalid FK
            "binding_energy": 1.0,
            "bohr_radius": 1.0,
            "calculated_at": datetime.utcnow(),
        }
        with pytest.raises(ValidationError):
            ExcitonResult(**data_invalid)





class TestResponseModels:
    """Test cases for utility response models"""

    def test_paginated_response(self):
        """Test PaginatedResponse model"""
        response = PaginatedResponse(
            total=100,
            page=1,
            page_size=20,
            items=[{"id": 1}, {"id": 2}]
        )

        assert response.total == 100
        assert response.page == 1
        assert response.page_size == 20
        assert len(response.items) == 2

    def test_error_response(self):
        """Test ErrorResponse model"""
        response = ErrorResponse(
            error="ValidationError",
            message="Invalid input",
            details={"field": "email"},
            request_id="req-123"
        )

        assert response.error == "ValidationError"
        assert response.message == "Invalid input"
        assert response.details == {"field": "email"}
        assert response.request_id == "req-123"

    def test_success_response(self):
        """Test SuccessResponse model"""
        response = SuccessResponse(
            success=True,
            message="Operation completed",
            data={"id": 1}
        )

        assert response.success is True
        assert response.message == "Operation completed"
        assert response.data == {"id": 1}


class TestPhysicsModels:
    """Test physics-specific validations and edge cases"""

    def test_material_gaas_realistic_values(self):
        """Test Material model with realistic GaAs properties"""
        gaas = Material(
            id=1,
            name="Gallium Arsenide",
            formula="GaAs",
            band_gap=1.42,  # eV
            epsilon=12.9,  # Dielectric constant
            effective_mass_e=0.067,  # Electron effective mass (m_e units)
            effective_mass_h=0.45,  # Hole effective mass (m_e units)
            lattice_constant=5.65  # Angstrom
        )

        assert gaas.band_gap > 0
        assert gaas.epsilon > 1  # Must be > vacuum permittivity
        assert 0 < gaas.effective_mass_e < 1  # Effective mass < actual electron mass
        assert 0 < gaas.effective_mass_h < 1

    def test_material_silicon_realistic_values(self):
        """Test Material model with realistic Silicon properties"""
        si = Material(
            id=2,
            name="Silicon",
            formula="Si",
            band_gap=1.12,  # eV
            epsilon=11.7,
            effective_mass_e=0.26,
            effective_mass_h=0.38,
            lattice_constant=5.43
        )

        assert si.band_gap > 0
        assert si.epsilon > 1
        assert 0 < si.effective_mass_e < 1
        assert 0 < si.effective_mass_h < 1

    def test_exciton_result_physical_ranges(self):
        """Test ExcitonResult has physically reasonable values"""
        result = ExcitonResult(
            id=1,
            material_id=1,
            binding_energy=0.004,  # ~4 meV (typical for GaAs)
            bohr_radius=10.0,  # ~10 nm (typical for GaAs)
            calculated_at=datetime.utcnow()
        )

        # Binding energy should be much smaller than band gap (<1 eV typically)
        assert 0 < result.binding_energy < 1.0

        # Bohr radius should be in nm range (1-100 nm typically)
        assert 0 < result.bohr_radius < 1000

    def test_material_wide_band_gap(self):
        """Test Material with wide band gap (e.g., GaN)"""
        gan = Material(
            id=3,
            name="Gallium Nitride",
            formula="GaN",
            band_gap=3.4,  # eV (wide band gap)
            epsilon=8.9,
            effective_mass_e=0.20,
            effective_mass_h=0.80,
            lattice_constant=3.19
        )

        # Wide band gap materials (> 2 eV) for LEDs/UV
        assert gan.band_gap > 2.0

    def test_material_narrow_band_gap(self):
        """Test Material with narrow band gap (e.g., InSb)"""
        insb = Material(
            id=4,
            name="Indium Antimonide",
            formula="InSb",
            band_gap=0.17,  # eV (narrow band gap)
            epsilon=16.8,
            effective_mass_e=0.014,
            effective_mass_h=0.40,
            lattice_constant=6.48
        )

        # Narrow band gap materials (< 1 eV) for IR detectors
        assert 0 < insb.band_gap < 1.0
