"""
Database connection and session management for dmca-light-api.

Generated by The Anvil S+++ Constitutional AGI Genesis Engine.

[!] CRITICAL: This file is auto-generated. Do not edit manually.
"""

from sqlmodel import SQLModel, create_engine, Session
from typing import Generator

from .config import settings

# Create database engine
engine = create_engine(
    settings.DATABASE_URL,
    echo=settings.DATABASE_ECHO,
    connect_args={"check_same_thread": False},  # SQLite specific
)


# SQLModel setup
def create_db_and_tables():
    """Create all database tables"""
    SQLModel.metadata.create_all(engine)


def get_session() -> Generator[Session, None, None]:
    """
    Dependency for getting database session.

    Usage:
        @app.get("/items/")
        def read_items(session: Session = Depends(get_session)):
            ...
    """
    with Session(engine) as session:
        yield session
