"""
FastAPI application entry point for dmca-light-api.

Generated by The Anvil S+++ Constitutional AGI Genesis Engine.
Version: 0.1.0

[!] CRITICAL: This file is auto-generated. Do not edit manually.
    To modify the app, update the Anvil specification YAML and regenerate.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.trustedhost import TrustedHostMiddleware
from fastapi.responses import JSONResponse
import logging
import sys
import textwrap

from .endpoints import router
from .config import settings

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger(__name__)

# Create FastAPI application
app = FastAPI(
    title="DMCA-Light: Exciton Calculator API",
    version="0.1.0",
    description=textwrap.dedent(
        """
        # DMCA-Light: Educational Exciton Calculator

        Educational REST API for calculating exciton properties in
        semiconductor materials using the Wannier model.

        ## Features

        * **Material Database**: Semiconductor materials with band
          structure properties
        * **Exciton Calculator**: Wannier model for binding energy and
          Bohr radius
        * **Material Selectors**: Recommend materials for solar cells
          and LEDs
        * **Educational Focus**: Simplified physics for learning
          purposes

        ## Physics Background

        ### Wannier Exciton Model

        Suitable for direct-gap semiconductors with large dielectric
        constants:

        **Binding Energy**:
        ```
        E_b = (μ * e⁴) / (2 * (4π * ε₀ * εᵣ)² * ℏ²)
        ```

        **Bohr Radius**:
        ```
        a_B = (4π * ε₀ * εᵣ * ℏ²) / (μ * e²)
        ```

        Where:
        - μ = reduced effective mass
        - εᵣ = relative permittivity (dielectric constant)
        - e = elementary charge
        - ℏ = reduced Planck constant

        ### Example Results

        - **GaAs**: E_b ≈ 4 meV, a_B ≈ 10 nm
        - **Si**: E_b ≈ 14 meV, a_B ≈ 4 nm
        - **GaN**: E_b ≈ 25 meV, a_B ≈ 3 nm

        ## Quick Start

        ### Calculate Exciton Properties

        ```python
        import requests

        material = {
            "id": 1,
            "name": "Gallium Arsenide",
            "formula": "GaAs",
            "band_gap": 1.42,
            "epsilon": 12.9,
            "effective_mass_e": 0.067,
            "effective_mass_h": 0.45,
            "lattice_constant": 5.65,
        }

        response = requests.post(
            "http://localhost:8000/api/v1/calculate/exciton",
            json=material,
        )
        result = response.json()
        print(f"Binding Energy: {result['binding_energy']:.4f} eV")
        print(f"Bohr Radius: {result['bohr_radius']:.2f} nm")
        ```

        ### Find Solar Cell Materials

        ```python
        response = requests.get(
            "http://localhost:8000/api/v1/selector/solar?top_n=5"
        )
        materials = response.json()
        for m in materials:
            print(f"{m['name']}: {m['band_gap']:.2f} eV")
        ```

        ## Full Version

        This is a simplified educational version. For production-grade
        calculations with ab initio methods, see **DMCA S++**.

        **Contact**: info@flamehaven.space | flamehaven01@gmail.com
        """
    ),
    contact={
        "name": "Flamehaven",
        "email": "info@flamehaven.space",
    },
    license_info={
        "name": "MIT License",
        "url": "https://opensource.org/licenses/MIT",
    },
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json",
    openapi_tags=[
        {
            "name": "materials",
            "description": "Material database operations (CRUD)",
        },
        {
            "name": "calculations",
            "description": "Exciton property calculations using Wannier model",
        },
        {
            "name": "selector",
            "description": "Material recommendation for specific applications",
        },
        {
            "name": "monitoring",
            "description": "Health check and system monitoring",
        },
    ],
)

# CORS middleware
# Standard CORS: Allow configured origins
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Trusted host middleware (security)
app.add_middleware(TrustedHostMiddleware, allowed_hosts=settings.ALLOWED_HOSTS)

# Include API router
app.include_router(router)


@app.on_event("startup")
async def startup_event():
    """Application startup event"""
    logger.info("Starting dmca-light-api v0.1.0")
    logger.info(f"Environment: {settings.ENVIRONMENT}")
    logger.info(f"Debug mode: {settings.DEBUG}")


@app.on_event("shutdown")
async def shutdown_event():
    """Application shutdown event"""
    logger.info("Shutting down dmca-light-api v0.1.0")


@app.exception_handler(Exception)
async def global_exception_handler(request, exc):
    """Global exception handler for unhandled errors"""
    logger.error(f"Unhandled exception: {exc}", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={
            "error": "InternalServerError",
            "message": "An unexpected error occurred",
            "details": str(exc) if settings.DEBUG else None,
        },
    )


@app.get("/")
async def root():
    """Root endpoint"""
    return {
        "project": "dmca-light-api",
        "version": "0.1.0",
        "description": "Educational API for dark matter exciton calculations",
        "docs": "/docs",
        "health": "/api/v1/health",
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "app.main:app",
        host=settings.HOST,
        port=settings.PORT,
        reload=settings.DEBUG,
        log_level="info",
    )
