"""
Domain models for dmca-light-api.

Generated by The Anvil S+++ Constitutional AGI Genesis Engine.
Version: 0.1.0

[!] CRITICAL: This file is auto-generated. Do not edit manually.
    To modify models, update the Anvil specification YAML and regenerate.
"""

from datetime import datetime
from typing import Optional, List

from pydantic import BaseModel, Field, field_validator


class Material(BaseModel):
    """Material properties for exciton calculations."""

    id: int = Field(..., primary_key=True)

    name: str = Field(...)

    formula: str = Field(...)

    band_gap: float = Field(...)

    epsilon: float = Field(...)

    effective_mass_e: float = Field(...)

    effective_mass_h: float = Field(...)

    lattice_constant: float = Field(...)

    @field_validator("*", mode="before")
    def sanitize_string_inputs(cls, v, info):
        """Sanitize string inputs to prevent XSS attacks."""
        if isinstance(v, str):
            if "\x00" in v:
                raise ValueError(
                    f"{info.field_name} contains invalid null bytes"
                )

            stripped = v.strip()
            if not stripped:
                raise ValueError(
                    f"{info.field_name} cannot be only whitespace"
                )

            return stripped
        return v

    class Config:
        """Pydantic model configuration"""

        # Allow ORM object conversion
        from_attributes = True
        # Validate on field assignment, not just initialization
        validate_assignment = True
        # Use enum values instead of enum objects in responses
        use_enum_values = True
        # Auto-strip string whitespace
        str_strip_whitespace = True
        json_schema_extra = {
            "examples": [
                {
                    "id": 1,
                    "name": "Gallium Arsenide",
                    "formula": "GaAs",
                    "band_gap": 1.42,
                    "epsilon": 12.9,
                    "effective_mass_e": 0.067,
                    "effective_mass_h": 0.45,
                    "lattice_constant": 5.65,
                },
                {
                    "id": 2,
                    "name": "Silicon",
                    "formula": "Si",
                    "band_gap": 1.12,
                    "epsilon": 11.7,
                    "effective_mass_e": 0.26,
                    "effective_mass_h": 0.38,
                    "lattice_constant": 5.43,
                },
                {
                    "id": 3,
                    "name": "Gallium Nitride",
                    "formula": "GaN",
                    "band_gap": 3.4,
                    "epsilon": 8.9,
                    "effective_mass_e": 0.20,
                    "effective_mass_h": 0.80,
                    "lattice_constant": 3.19,
                },
            ]
        }


class ExcitonResult(BaseModel):
    """Exciton calculation result."""

    id: int = Field(..., primary_key=True)

    material_id: int = Field(...)

    binding_energy: float = Field(...)

    bohr_radius: float = Field(...)

    calculated_at: datetime = Field(...)

    # Foreign key validators
    @field_validator("material_id")
    def validate_material_id(cls, v):
        """Validate foreign key reference to Material.id"""
        if v is not None and v <= 0:
            raise ValueError(
                "material_id must be a positive integer (valid foreign key)"
            )
        return v

    class Config:
        """Pydantic model configuration"""

        # Allow ORM object conversion
        from_attributes = True
        # Validate on field assignment, not just initialization
        validate_assignment = True
        # Use enum values instead of enum objects in responses
        use_enum_values = True
        # Auto-strip string whitespace
        str_strip_whitespace = True
        json_schema_extra = {
            "examples": [
                {
                    "id": 1,
                    "material_id": 1,
                    "binding_energy": 0.0045,
                    "bohr_radius": 11.2,
                    "calculated_at": "2025-11-26T00:00:00",
                    "description": (
                        "GaAs exciton: ~4.5 meV binding, ~11 nm Bohr radius"
                    ),
                },
                {
                    "id": 2,
                    "material_id": 2,
                    "binding_energy": 0.0147,
                    "bohr_radius": 4.3,
                    "calculated_at": "2025-11-26T00:00:00",
                    "description": (
                        "Si exciton: ~15 meV binding, ~4 nm Bohr radius"
                    ),
                },
                {
                    "id": 3,
                    "material_id": 3,
                    "binding_energy": 0.0256,
                    "bohr_radius": 2.8,
                    "calculated_at": "2025-11-26T00:00:00",
                    "description": (
                        "GaN exciton: ~26 meV binding, ~3 nm Bohr radius"
                    ),
                },
            ]
        }


class PaginatedResponse(BaseModel):
    """Generic paginated response wrapper"""

    total: int = Field(..., description="Total number of items")
    page: int = Field(
        ..., description="Current page number (1-indexed)"
    )
    page_size: int = Field(..., description="Items per page")
    items: List[dict] = Field(
        default_factory=list, description="List of items"
    )

    class Config:
        from_attributes = True


class ErrorResponse(BaseModel):
    """Standard error response"""

    error: str = Field(..., description="Error type")
    message: str = Field(..., description="Human-readable error message")
    details: Optional[dict] = Field(
        default=None, description="Additional error details"
    )
    request_id: Optional[str] = Field(
        default=None, description="Request ID for tracing"
    )

    class Config:
        from_attributes = True


class SuccessResponse(BaseModel):
    """Standard success response"""

    success: bool = Field(
        default=True, description="Operation success status"
    )
    message: str = Field(..., description="Success message")
    data: Optional[dict] = Field(
        default=None, description="Response data payload"
    )

    class Config:
        from_attributes = True
